export interface ImgurImageUploadEntity {
    data: {
        id: string,
        title: string | null,
        description: string | null,
        datetime: number,
        type: string,
        animated: boolean,
        width: number,
        height: number,
        size: number,
        views: number,
        bandwidth: number,
        vote: string | null,
        favorite: boolean,
        nsfw: boolean | null,
        section: string | null,
        account_url: string | null,
        account_id: number,
        is_ad: boolean,
        in_most_viral: boolean,
        tags: string[],
        ad_type: number,
        ad_url: string,
        in_gallery: boolean,
        deletehash: string,
        name: string,
        link: string,
    },
    success: boolean,
    status: number,
}
